services:
  livekit:
    image: livekit/livekit-server:v1.8.4
    command: --config /etc/livekit/config.yaml
    network_mode: host
    volumes:
      - ./livekit-config.yaml:/etc/livekit/config.yaml
      - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.432bleu.com:/etc/caddy-certs:ro
    depends_on:
      redis:
        condition: service_started

  back:
    environment:
      LIVEKIT_HOST: "$LIVEKIT_HOST"
      LIVEKIT_API_KEY: "$LIVEKIT_API_KEY"
      LIVEKIT_API_SECRET: "$LIVEKIT_API_SECRET"
      MAX_USERS_FOR_WEBRTC: "$MAX_USERS_FOR_WEBRTC"
