"""Minimal OpenID Connect provider for WorkAdventure staff login.

boxoffice is the IdP (see scripts/vps/OIDC-PLAN.md): the existing magic-link
login (auth.py) authenticates the human; these endpoints are the protocol shell
that lets WorkAdventure's openid-client consume that session.

Shaped by what openid-client actually does (traced in play/src/pusher/services/
OpenIDClient.ts):
  - discovers endpoints via /.well-known/openid-configuration (no manual config)
  - validates the id_token RS256 signature against jwks_uri
  - ALWAYS sends PKCE S256 (code_challenge/code_verifier); never sends nonce
  - reads user claims — including tags — from /userinfo, NOT from the id_token
  - appends non-standard query params (playUri, manuallyTriggered, ...) to
    /authorize; they must be ignored, never echoed
  - verifies the userinfo `sub` matches the id_token `sub`

Anyone with a member session can log in; permissions come only from tags, which
come only from OIDC_STAFF_TAGS — a logged-in member with no entry there gets
`tags: []` and no powers, same as an anonymous attendee.

Mounted at the app root (not /api): discovery must live at the well-known path.
"""

import base64
import hashlib
import os
import secrets
from datetime import datetime, timedelta, timezone

import jwt
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse, RedirectResponse, Response
from sqlalchemy.orm import Session

from ..database import get_db
from ..limiter import limiter
from ..models import AuthCode
from ..session import get_current_email

router = APIRouter()

ISSUER = os.getenv("OIDC_ISSUER", os.getenv("BOXOFFICE_DOMAIN", "https://432bleu.com")).rstrip("/")
CLIENT_ID = os.getenv("OIDC_CLIENT_ID", "wa-play")
CLIENT_SECRET = os.getenv("OIDC_CLIENT_SECRET", "")
REDIRECT_URIS = [u.strip() for u in os.getenv(
    "OIDC_REDIRECT_URIS", "https://play.432bleu.com/openid-callback"
).split(",") if u.strip()]

CODE_TTL_SECONDS = 60
TOKEN_TTL_SECONDS = 3600
NEXT_COOKIE = "bleu_next"

# ---- signing key ------------------------------------------------------------
# Base64-wrapped PEM in .env (multiline PEM does not survive .env/compose).
# Generated by scripts/vps/setup-secrets.sh. Empty = provider disabled (503),
# not a crash: boxoffice's core job is selling tickets, not OIDC.
_PRIVATE_KEY_PEM = base64.b64decode(os.getenv("OIDC_PRIVATE_KEY_B64", "")) or None

_PUBLIC_KEY = None
_KID = None
_JWK = None

if _PRIVATE_KEY_PEM:
    from cryptography.hazmat.primitives import serialization

    _private_key = serialization.load_pem_private_key(_PRIVATE_KEY_PEM, password=None)
    _PUBLIC_KEY = _private_key.public_key()

    _der = _PUBLIC_KEY.public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    _KID = hashlib.sha256(_der).hexdigest()[:16]

    def _b64url_uint(n: int) -> str:
        raw = n.to_bytes((n.bit_length() + 7) // 8, "big")
        return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()

    _numbers = _PUBLIC_KEY.public_numbers()
    _JWK = {
        "kty": "RSA",
        "use": "sig",
        "alg": "RS256",
        "kid": _KID,
        "n": _b64url_uint(_numbers.n),
        "e": _b64url_uint(_numbers.e),
    }


def _require_configured():
    if not (_PRIVATE_KEY_PEM and CLIENT_SECRET):
        raise HTTPException(status_code=503, detail="OIDC is not configured")


# ---- staff tags -------------------------------------------------------------
# OIDC_STAFF_TAGS="skyler@example.com=admin,editor;tech@example.com=editor"
def _tags_for(email: str) -> list[str]:
    raw = os.getenv("OIDC_STAFF_TAGS", "")
    for entry in raw.split(";"):
        entry = entry.strip()
        if not entry or "=" not in entry:
            continue
        addr, _, tags = entry.partition("=")
        if addr.strip().lower() == email.lower():
            return [t.strip() for t in tags.split(",") if t.strip()]
    return []


def _claims_for(email: str) -> dict:
    username = email.split("@", 1)[0]
    return {
        "sub": email,  # userinfo sub MUST match the id_token sub (openid-client checks)
        "email": email,
        "email_verified": True,  # magic-link login proves mailbox control
        "username": username,  # WA's OPID_USERNAME_CLAIM default is "username"
        "preferred_username": username,
        "tags": _tags_for(email),
    }


# ---- discovery --------------------------------------------------------------
@router.get("/.well-known/openid-configuration")
def discovery():
    return {
        "issuer": ISSUER,
        "authorization_endpoint": f"{ISSUER}/authorize",
        "token_endpoint": f"{ISSUER}/token",
        "userinfo_endpoint": f"{ISSUER}/userinfo",
        "jwks_uri": f"{ISSUER}/.well-known/jwks.json",
        "response_types_supported": ["code"],
        "grant_types_supported": ["authorization_code"],
        "subject_types_supported": ["public"],
        "id_token_signing_alg_values_supported": ["RS256"],
        "scopes_supported": ["openid", "email", "profile"],
        "token_endpoint_auth_methods_supported": ["client_secret_basic", "client_secret_post"],
        "code_challenge_methods_supported": ["S256"],
        "claims_supported": ["sub", "email", "email_verified", "username", "preferred_username", "tags"],
    }


@router.get("/.well-known/jwks.json")
def jwks():
    _require_configured()
    return {"keys": [_JWK]}


# ---- /authorize -------------------------------------------------------------
@router.get("/authorize")
@limiter.limit("20/minute")
def authorize(request: Request, db: Session = Depends(get_db)):
    _require_configured()
    q = request.query_params

    # client_id / redirect_uri failures MUST NOT redirect — redirecting an
    # unvalidated URI is the classic open-redirect / code-leak hole.
    if q.get("client_id") != CLIENT_ID:
        raise HTTPException(status_code=400, detail="Unknown client_id")
    redirect_uri = q.get("redirect_uri", "")
    if redirect_uri not in REDIRECT_URIS:  # exact match only, never prefix
        raise HTTPException(status_code=400, detail="redirect_uri not allowed")

    def err(code: str):
        sep = "&" if "?" in redirect_uri else "?"
        state = q.get("state", "")
        return RedirectResponse(f"{redirect_uri}{sep}error={code}&state={state}", status_code=302)

    if q.get("response_type") != "code":
        return err("unsupported_response_type")
    # WA always sends PKCE S256; require it so a stolen code is useless alone.
    if q.get("code_challenge_method") != "S256" or not q.get("code_challenge"):
        return err("invalid_request")

    try:
        email = get_current_email(request)
    except HTTPException:
        # Not logged in: remember where to resume, then hand off to the
        # magic-link login. auth.py's verify endpoint honors bleu_next.
        response = RedirectResponse("/login", status_code=302)
        next_url = "/authorize?" + str(request.query_params)
        response.set_cookie(
            NEXT_COOKIE, next_url,
            max_age=600, httponly=True, secure=True, samesite="lax", path="/",
        )
        return response

    code = secrets.token_urlsafe(32)
    db.add(AuthCode(
        code_hash=hashlib.sha256(code.encode()).hexdigest(),
        email=email,
        client_id=CLIENT_ID,
        redirect_uri=redirect_uri,
        code_challenge=q.get("code_challenge"),
        expires_at=datetime.now(timezone.utc) + timedelta(seconds=CODE_TTL_SECONDS),
    ))
    # Opportunistic cleanup, same pattern as login_tokens.
    db.query(AuthCode).filter(
        AuthCode.created_at < datetime.now(timezone.utc) - timedelta(hours=1)
    ).delete()
    db.commit()

    sep = "&" if "?" in redirect_uri else "?"
    state = q.get("state", "")
    return RedirectResponse(f"{redirect_uri}{sep}code={code}&state={state}", status_code=302)


# ---- /token -----------------------------------------------------------------
def _client_auth_ok(request: Request, form: dict) -> bool:
    """Accept client_secret_basic (openid-client's default) and client_secret_post."""
    auth = request.headers.get("authorization", "")
    if auth.lower().startswith("basic "):
        try:
            decoded = base64.b64decode(auth[6:]).decode()
            got_id, _, got_secret = decoded.partition(":")
        except Exception:
            return False
    else:
        got_id = form.get("client_id", "")
        got_secret = form.get("client_secret", "")
    return secrets.compare_digest(got_id, CLIENT_ID) and secrets.compare_digest(got_secret, CLIENT_SECRET)


@router.post("/token")
@limiter.limit("20/minute")
async def token(request: Request, db: Session = Depends(get_db)):
    _require_configured()
    form = dict(await request.form())

    if not _client_auth_ok(request, form):
        return JSONResponse(
            {"error": "invalid_client"}, status_code=401,
            headers={"WWW-Authenticate": 'Basic realm="oidc"'},
        )
    if form.get("grant_type") != "authorization_code":
        return JSONResponse({"error": "unsupported_grant_type"}, status_code=400)

    code = form.get("code", "")
    row = db.query(AuthCode).filter(
        AuthCode.code_hash == hashlib.sha256(code.encode()).hexdigest()
    ).first() if code else None

    now = datetime.now(timezone.utc)
    if (
        row is None
        or row.used_at is not None
        or row.expires_at.replace(tzinfo=timezone.utc) < now
        or row.client_id != CLIENT_ID
        or row.redirect_uri != form.get("redirect_uri", "")
    ):
        return JSONResponse({"error": "invalid_grant"}, status_code=400)

    # PKCE: base64url(SHA256(verifier)) must equal the challenge the code was
    # minted with. This is what makes an intercepted code worthless.
    verifier = form.get("code_verifier", "")
    challenge = base64.urlsafe_b64encode(
        hashlib.sha256(verifier.encode()).digest()
    ).rstrip(b"=").decode()
    if not secrets.compare_digest(challenge, row.code_challenge):
        return JSONResponse({"error": "invalid_grant"}, status_code=400)

    row.used_at = now
    db.commit()

    base = {"iss": ISSUER, "iat": now, "exp": now + timedelta(seconds=TOKEN_TTL_SECONDS)}
    id_token = jwt.encode(
        {**base, **_claims_for(row.email), "aud": CLIENT_ID},
        _PRIVATE_KEY_PEM, algorithm="RS256", headers={"kid": _KID},
    )
    # Access token is a self-contained JWT (aud-scoped to userinfo) rather than
    # a DB row — nothing to store or clean up, and /userinfo just verifies it.
    access_token = jwt.encode(
        {**base, "sub": row.email, "aud": f"{ISSUER}/userinfo"},
        _PRIVATE_KEY_PEM, algorithm="RS256", headers={"kid": _KID},
    )
    return {
        "access_token": access_token,
        "id_token": id_token,
        "token_type": "Bearer",
        "expires_in": TOKEN_TTL_SECONDS,
    }


# ---- /userinfo --------------------------------------------------------------
@router.get("/userinfo")
@limiter.limit("60/minute")
def userinfo(request: Request):
    _require_configured()
    auth = request.headers.get("authorization", "")
    if not auth.lower().startswith("bearer "):
        return Response(status_code=401, headers={"WWW-Authenticate": "Bearer"})
    try:
        claims = jwt.decode(
            auth[7:], _PUBLIC_KEY, algorithms=["RS256"], audience=f"{ISSUER}/userinfo"
        )
    except jwt.InvalidTokenError:
        return Response(status_code=401, headers={"WWW-Authenticate": 'Bearer error="invalid_token"'})
    # Tags are re-read from env here, not frozen into the token: /userinfo is
    # where WA actually takes claims from, so an OIDC_STAFF_TAGS change applies
    # on the next login rather than after token expiry.
    return _claims_for(claims["sub"])
